const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  window: {
    minimize: () => ipcRenderer.invoke('window:minimize'),
    maximize: () => ipcRenderer.invoke('window:maximize'),
    close: () => ipcRenderer.invoke('window:close'),
    isMaximized: () => ipcRenderer.invoke('window:isMaximized'),
  },
  mc: {
    getManifest: () => ipcRenderer.invoke('mc:getManifest'),
    getVersionInfo: (id) => ipcRenderer.invoke('mc:getVersionInfo', id),
    downloadVersion: (id) => ipcRenderer.invoke('mc:downloadVersion', id),
    launch: (id) => ipcRenderer.invoke('mc:launch', id),
    onDownloadProgress: (callback) => {
      ipcRenderer.on('mc:downloadProgress', (_e, data) => callback(data));
    },
    onGameLog: (callback) => {
      ipcRenderer.on('mc:gameLog', (_e, data) => callback(data));
    },
    onGameClosed: (callback) => {
      ipcRenderer.on('mc:gameClosed', (_e, code) => callback(code));
    },
    getInstalledVersions: () => ipcRenderer.invoke('mc:getInstalledVersions'),
    deleteVersion: (id) => ipcRenderer.invoke('mc:deleteVersion', id),
    openFolder: () => ipcRenderer.invoke('mc:openFolder'),
    getMods: (versionId) => ipcRenderer.invoke('mc:getMods', versionId),
    importMod: (versionId, sourcePath) => ipcRenderer.invoke('mc:importMod', versionId, sourcePath),
    importMods: (versionId, files) => ipcRenderer.invoke('mc:importMods', versionId, files),
    deleteMod: (versionId, filename) => ipcRenderer.invoke('mc:deleteMod', versionId, filename),
    getFabricVersions: (mcVersion) => ipcRenderer.invoke('mc:getFabricVersions', mcVersion),
    getForgeVersions: (mcVersion) => ipcRenderer.invoke('mc:getForgeVersions', mcVersion),
    installFabric: (mcVersion, loaderVersion) => ipcRenderer.invoke('mc:installFabric', mcVersion, loaderVersion),
    installForge: (mcVersion, forgeVersion) => ipcRenderer.invoke('mc:installForge', mcVersion, forgeVersion),
    getSettings: () => ipcRenderer.invoke('mc:getSettings'),
    saveSettings: (settings) => ipcRenderer.invoke('mc:saveSettings', settings),
    getAccounts: () => ipcRenderer.invoke('mc:getAccounts'),
    getActiveAccount: () => ipcRenderer.invoke('mc:getActiveAccount'),
    setActiveAccount: (id) => ipcRenderer.invoke('mc:setActiveAccount', id),
    addOfflineAccount: (username) => ipcRenderer.invoke('mc:addOfflineAccount', username),
    removeAccount: (id) => ipcRenderer.invoke('mc:removeAccount', id),
    startMicrosoftLogin: () => ipcRenderer.invoke('mc:startMicrosoftLogin'),
    loginThirdParty: (serverUrl, username, password) => ipcRenderer.invoke('mc:loginThirdParty', serverUrl, username, password),
    getWorlds: () => ipcRenderer.invoke('mc:getWorlds'),
    deleteWorld: (name) => ipcRenderer.invoke('mc:deleteWorld', name),
    backupWorld: (name) => ipcRenderer.invoke('mc:backupWorld', name),
    openWorldsFolder: () => ipcRenderer.invoke('mc:openWorldsFolder'),
    getWorldIcon: (name) => ipcRenderer.invoke('mc:getWorldIcon', name),
    getResourcePacks: () => ipcRenderer.invoke('mc:getResourcePacks'),
    importResourcePacks: (files) => ipcRenderer.invoke('mc:importResourcePacks', files),
    deleteResourcePack: (name) => ipcRenderer.invoke('mc:deleteResourcePack', name),
    openResourcePacksFolder: () => ipcRenderer.invoke('mc:openResourcePacksFolder'),
    getOptiFineVersions: (mcVersion) => ipcRenderer.invoke('mc:getOptiFineVersions', mcVersion),
    installOptiFine: (mcVersion, optiVersion) => ipcRenderer.invoke('mc:installOptiFine', mcVersion, optiVersion),
    getNeoForgeVersions: (mcVersion) => ipcRenderer.invoke('mc:getNeoForgeVersions', mcVersion),
    installNeoForge: (mcVersion, version) => ipcRenderer.invoke('mc:installNeoForge', mcVersion, version),
    getQuiltVersions: (mcVersion) => ipcRenderer.invoke('mc:getQuiltVersions', mcVersion),
    installQuilt: (mcVersion, version) => ipcRenderer.invoke('mc:installQuilt', mcVersion, version),
    getCustomGameDirs: () => ipcRenderer.invoke('mc:getCustomGameDirs'),
    setCustomGameDir: (versionId, dir) => ipcRenderer.invoke('mc:setCustomGameDir', versionId, dir),
    removeCustomGameDir: (versionId) => ipcRenderer.invoke('mc:removeCustomGameDir', versionId),
    getAutoMemory: () => ipcRenderer.invoke('mc:getAutoMemory'),
    getVersionChangelog: (versionId) => ipcRenderer.invoke('mc:getVersionChangelog', versionId),
    getMinecraftNews: () => ipcRenderer.invoke('mc:getMinecraftNews'),
    searchModrinth: (query, page, projectType) => ipcRenderer.invoke('mc:searchModrinth', query, page, projectType),
    getModrinthPopular: (projectType) => ipcRenderer.invoke('mc:getModrinthPopular', projectType),
    getModrinthMod: (slug) => ipcRenderer.invoke('mc:getModrinthMod', slug),
    getModrinthVersions: (slug, mcVersion, projectType) => ipcRenderer.invoke('mc:getModrinthVersions', slug, mcVersion, projectType),
    downloadMod: (versionId, url, filename, destType) => ipcRenderer.invoke('mc:downloadMod', versionId, url, filename, destType),
    parseModpack: (filePath) => ipcRenderer.invoke('mc:parseModpack', filePath),
    installModpack: (pack) => ipcRenderer.invoke('mc:installModpack', pack),
    exportModpack: (versionId, format) => ipcRenderer.invoke('mc:exportModpack', versionId, format),
    getServers: () => ipcRenderer.invoke('mc:getServers'),
    addServer: (name, address, port) => ipcRenderer.invoke('mc:addServer', name, address, port),
    removeServer: (id) => ipcRenderer.invoke('mc:removeServer', id),
    pingServer: (id, address, port) => ipcRenderer.invoke('mc:pingServer', id, address, port),
    checkCrashReports: () => ipcRenderer.invoke('mc:checkCrashReports'),
    getCrashSuggestion: (crash) => ipcRenderer.invoke('mc:getCrashSuggestion', crash),
    validateLaunch: (versionId) => ipcRenderer.invoke('mc:validateLaunch', versionId),
    cloneVersion: (versionId, newName) => ipcRenderer.invoke('mc:cloneVersion', versionId, newName),
    renameVersion: (versionId, newName) => ipcRenderer.invoke('mc:renameVersion', versionId, newName),
    getInstanceSettings: (versionId) => ipcRenderer.invoke('mc:getInstanceSettings', versionId),
    setInstanceSettings: (versionId, patch) => ipcRenderer.invoke('mc:setInstanceSettings', versionId, patch),
    downloadQueueAdd: (item) => ipcRenderer.invoke('mc:downloadQueueAdd', item),
    downloadQueuePause: (id) => ipcRenderer.invoke('mc:downloadQueuePause', id),
    downloadQueueResume: (id) => ipcRenderer.invoke('mc:downloadQueueResume', id),
    downloadQueueCancel: (id) => ipcRenderer.invoke('mc:downloadQueueCancel', id),
    downloadQueueGet: () => ipcRenderer.invoke('mc:downloadQueueGet'),
    toggleMod: (versionId, filename) => ipcRenderer.invoke('mc:toggleMod', versionId, filename),
    getModDependencies: (versionId) => ipcRenderer.invoke('mc:getModDependencies', versionId),
    getModrinthVersionFile: (versionId) => ipcRenderer.invoke('mc:getModrinthVersionFile', versionId),
    checkModUpdates: (slugs) => ipcRenderer.invoke('mc:checkModUpdates', slugs),
    getScreenshots: () => ipcRenderer.invoke('mc:getScreenshots'),
    getScreenshotBase64: (name) => ipcRenderer.invoke('mc:getScreenshotBase64', name),
    deleteScreenshot: (name) => ipcRenderer.invoke('mc:deleteScreenshot', name),
    openScreenshotsFolder: () => ipcRenderer.invoke('mc:openScreenshotsFolder'),
    checkNewVersion: () => ipcRenderer.invoke('mc:checkNewVersion'),
    getFriendsSnapshot: () => ipcRenderer.invoke('mc:getFriendsSnapshot'),
    addFriend: (name, ip) => ipcRenderer.invoke('mc:addFriend', name, ip),
    removeFriend: (id) => ipcRenderer.invoke('mc:removeFriend', id),
    copyServerAddress: (ip, port) => ipcRenderer.invoke('mc:copyServerAddress', ip, port),
    generateInviteCode: () => ipcRenderer.invoke('mc:generateInviteCode'),
    resolveInviteCode: (code) => ipcRenderer.invoke('mc:resolveInviteCode', code),
    checkModsForUpdates: (versionId) => ipcRenderer.invoke('mc:checkModsForUpdates', versionId),
    detectModConflicts: (versionId) => ipcRenderer.invoke('mc:detectModConflicts', versionId),
    updateAllMods: (versionId) => ipcRenderer.invoke('mc:updateAllMods', versionId),
    onGameStats: (callback) => {
      ipcRenderer.on('mc:gameStats', (_e, data) => callback(data));
    },
    searchCurseForge: (query, gameVersion) => ipcRenderer.invoke('mc:searchCurseForge', query, gameVersion),
    getCurseForgeFiles: (modId, gameVersion) => ipcRenderer.invoke('mc:getCurseForgeFiles', modId, gameVersion),
    checkForUpdates: () => ipcRenderer.invoke('mc:checkForUpdates'),
    downloadUpdate: () => ipcRenderer.invoke('mc:downloadUpdate'),
    openUpdateFolder: () => ipcRenderer.invoke('mc:openUpdateFolder'),
    onUpdateProgress: (callback) => {
      ipcRenderer.on('mc:updateProgress', (_e, data) => callback(data));
    },
    getErrorLog: () => ipcRenderer.invoke('mc:getErrorLog'),
    clearErrorLog: () => ipcRenderer.invoke('mc:clearErrorLog'),
    importMinecraftFolder: (folderPath) => ipcRenderer.invoke('mc:importMinecraftFolder', folderPath),
  },
});
